export default {
  login: 'unclejide1',
  id: 53279092,
  node_id: 'MDQ6VXNlcjUzMjc5MDky',
  avatar_url: 'https://avatars.githubusercontent.com/u/53279092?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/unclejide1',
  html_url: 'https://github.com/unclejide1',
  followers_url: 'https://api.github.com/users/unclejide1/followers',
  following_url:
    'https://api.github.com/users/unclejide1/following{/other_user}',
  gists_url: 'https://api.github.com/users/unclejide1/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/unclejide1/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/unclejide1/subscriptions',
  organizations_url: 'https://api.github.com/users/unclejide1/orgs',
  repos_url: 'https://api.github.com/users/unclejide1/repos',
  events_url: 'https://api.github.com/users/unclejide1/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/unclejide1/received_events',
  type: 'User',
  site_admin: false,
  name: 'Nwoke Jideofor Justice',
  company: '@decadevs ',
  blog: 'https://decagonhq.com/',
  location: 'Lagos, Nigeria.',
  email: null,
  hireable: true,
  bio: 'Software Engineer, \r\nfluent in java, javascript, react and python.',
  twitter_username: null,
  public_repos: 82,
  public_gists: 0,
  followers: 13,
  following: 34,
  created_at: '2019-07-24T21:35:10Z',
  updated_at: '2021-02-16T16:39:36Z',
};