export default[
  {
    login: 'KristofaJosh',
    id: 48376769,
    node_id: 'MDQ6VXNlcjQ4Mzc2NzY5',
    avatar_url: 'https://avatars.githubusercontent.com/u/48376769?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/KristofaJosh',
    html_url: 'https://github.com/KristofaJosh',
    followers_url: 'https://api.github.com/users/KristofaJosh/followers',
    following_url:
      'https://api.github.com/users/KristofaJosh/following{/other_user}',
    gists_url: 'https://api.github.com/users/KristofaJosh/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/KristofaJosh/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/KristofaJosh/subscriptions',
    organizations_url: 'https://api.github.com/users/KristofaJosh/orgs',
    repos_url: 'https://api.github.com/users/KristofaJosh/repos',
    events_url: 'https://api.github.com/users/KristofaJosh/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/KristofaJosh/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'OreAkintobi',
    id: 8383707,
    node_id: 'MDQ6VXNlcjgzODM3MDc=',
    avatar_url: 'https://avatars.githubusercontent.com/u/8383707?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/OreAkintobi',
    html_url: 'https://github.com/OreAkintobi',
    followers_url: 'https://api.github.com/users/OreAkintobi/followers',
    following_url:
      'https://api.github.com/users/OreAkintobi/following{/other_user}',
    gists_url: 'https://api.github.com/users/OreAkintobi/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/OreAkintobi/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/OreAkintobi/subscriptions',
    organizations_url: 'https://api.github.com/users/OreAkintobi/orgs',
    repos_url: 'https://api.github.com/users/OreAkintobi/repos',
    events_url: 'https://api.github.com/users/OreAkintobi/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/OreAkintobi/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'victor-onu',
    id: 49398011,
    node_id: 'MDQ6VXNlcjQ5Mzk4MDEx',
    avatar_url: 'https://avatars.githubusercontent.com/u/49398011?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/victor-onu',
    html_url: 'https://github.com/victor-onu',
    followers_url: 'https://api.github.com/users/victor-onu/followers',
    following_url:
      'https://api.github.com/users/victor-onu/following{/other_user}',
    gists_url: 'https://api.github.com/users/victor-onu/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/victor-onu/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/victor-onu/subscriptions',
    organizations_url: 'https://api.github.com/users/victor-onu/orgs',
    repos_url: 'https://api.github.com/users/victor-onu/repos',
    events_url: 'https://api.github.com/users/victor-onu/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/victor-onu/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'dizsart',
    id: 55360356,
    node_id: 'MDQ6VXNlcjU1MzYwMzU2',
    avatar_url: 'https://avatars.githubusercontent.com/u/55360356?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/dizsart',
    html_url: 'https://github.com/dizsart',
    followers_url: 'https://api.github.com/users/dizsart/followers',
    following_url:
      'https://api.github.com/users/dizsart/following{/other_user}',
    gists_url: 'https://api.github.com/users/dizsart/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/dizsart/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/dizsart/subscriptions',
    organizations_url: 'https://api.github.com/users/dizsart/orgs',
    repos_url: 'https://api.github.com/users/dizsart/repos',
    events_url: 'https://api.github.com/users/dizsart/events{/privacy}',
    received_events_url: 'https://api.github.com/users/dizsart/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Nnaji-Victor',
    id: 37231697,
    node_id: 'MDQ6VXNlcjM3MjMxNjk3',
    avatar_url: 'https://avatars.githubusercontent.com/u/37231697?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Nnaji-Victor',
    html_url: 'https://github.com/Nnaji-Victor',
    followers_url: 'https://api.github.com/users/Nnaji-Victor/followers',
    following_url:
      'https://api.github.com/users/Nnaji-Victor/following{/other_user}',
    gists_url: 'https://api.github.com/users/Nnaji-Victor/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/Nnaji-Victor/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/Nnaji-Victor/subscriptions',
    organizations_url: 'https://api.github.com/users/Nnaji-Victor/orgs',
    repos_url: 'https://api.github.com/users/Nnaji-Victor/repos',
    events_url: 'https://api.github.com/users/Nnaji-Victor/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Nnaji-Victor/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Dolapo47',
    id: 22444033,
    node_id: 'MDQ6VXNlcjIyNDQ0MDMz',
    avatar_url: 'https://avatars.githubusercontent.com/u/22444033?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Dolapo47',
    html_url: 'https://github.com/Dolapo47',
    followers_url: 'https://api.github.com/users/Dolapo47/followers',
    following_url:
      'https://api.github.com/users/Dolapo47/following{/other_user}',
    gists_url: 'https://api.github.com/users/Dolapo47/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Dolapo47/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Dolapo47/subscriptions',
    organizations_url: 'https://api.github.com/users/Dolapo47/orgs',
    repos_url: 'https://api.github.com/users/Dolapo47/repos',
    events_url: 'https://api.github.com/users/Dolapo47/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Dolapo47/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'weylar',
    id: 31368523,
    node_id: 'MDQ6VXNlcjMxMzY4NTIz',
    avatar_url: 'https://avatars.githubusercontent.com/u/31368523?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/weylar',
    html_url: 'https://github.com/weylar',
    followers_url: 'https://api.github.com/users/weylar/followers',
    following_url: 'https://api.github.com/users/weylar/following{/other_user}',
    gists_url: 'https://api.github.com/users/weylar/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/weylar/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/weylar/subscriptions',
    organizations_url: 'https://api.github.com/users/weylar/orgs',
    repos_url: 'https://api.github.com/users/weylar/repos',
    events_url: 'https://api.github.com/users/weylar/events{/privacy}',
    received_events_url: 'https://api.github.com/users/weylar/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'samicey',
    id: 49449271,
    node_id: 'MDQ6VXNlcjQ5NDQ5Mjcx',
    avatar_url: 'https://avatars.githubusercontent.com/u/49449271?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/samicey',
    html_url: 'https://github.com/samicey',
    followers_url: 'https://api.github.com/users/samicey/followers',
    following_url:
      'https://api.github.com/users/samicey/following{/other_user}',
    gists_url: 'https://api.github.com/users/samicey/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/samicey/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/samicey/subscriptions',
    organizations_url: 'https://api.github.com/users/samicey/orgs',
    repos_url: 'https://api.github.com/users/samicey/repos',
    events_url: 'https://api.github.com/users/samicey/events{/privacy}',
    received_events_url: 'https://api.github.com/users/samicey/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'folly77folly',
    id: 55381588,
    node_id: 'MDQ6VXNlcjU1MzgxNTg4',
    avatar_url: 'https://avatars.githubusercontent.com/u/55381588?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/folly77folly',
    html_url: 'https://github.com/folly77folly',
    followers_url: 'https://api.github.com/users/folly77folly/followers',
    following_url:
      'https://api.github.com/users/folly77folly/following{/other_user}',
    gists_url: 'https://api.github.com/users/folly77folly/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/folly77folly/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/folly77folly/subscriptions',
    organizations_url: 'https://api.github.com/users/folly77folly/orgs',
    repos_url: 'https://api.github.com/users/folly77folly/repos',
    events_url: 'https://api.github.com/users/folly77folly/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/folly77folly/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'amahJennifer',
    id: 36115754,
    node_id: 'MDQ6VXNlcjM2MTE1NzU0',
    avatar_url: 'https://avatars.githubusercontent.com/u/36115754?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/amahJennifer',
    html_url: 'https://github.com/amahJennifer',
    followers_url: 'https://api.github.com/users/amahJennifer/followers',
    following_url:
      'https://api.github.com/users/amahJennifer/following{/other_user}',
    gists_url: 'https://api.github.com/users/amahJennifer/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/amahJennifer/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/amahJennifer/subscriptions',
    organizations_url: 'https://api.github.com/users/amahJennifer/orgs',
    repos_url: 'https://api.github.com/users/amahJennifer/repos',
    events_url: 'https://api.github.com/users/amahJennifer/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/amahJennifer/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'iceboss3d',
    id: 28626956,
    node_id: 'MDQ6VXNlcjI4NjI2OTU2',
    avatar_url: 'https://avatars.githubusercontent.com/u/28626956?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/iceboss3d',
    html_url: 'https://github.com/iceboss3d',
    followers_url: 'https://api.github.com/users/iceboss3d/followers',
    following_url:
      'https://api.github.com/users/iceboss3d/following{/other_user}',
    gists_url: 'https://api.github.com/users/iceboss3d/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/iceboss3d/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/iceboss3d/subscriptions',
    organizations_url: 'https://api.github.com/users/iceboss3d/orgs',
    repos_url: 'https://api.github.com/users/iceboss3d/repos',
    events_url: 'https://api.github.com/users/iceboss3d/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/iceboss3d/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'EstherSeyi',
    id: 40301524,
    node_id: 'MDQ6VXNlcjQwMzAxNTI0',
    avatar_url: 'https://avatars.githubusercontent.com/u/40301524?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/EstherSeyi',
    html_url: 'https://github.com/EstherSeyi',
    followers_url: 'https://api.github.com/users/EstherSeyi/followers',
    following_url:
      'https://api.github.com/users/EstherSeyi/following{/other_user}',
    gists_url: 'https://api.github.com/users/EstherSeyi/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/EstherSeyi/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/EstherSeyi/subscriptions',
    organizations_url: 'https://api.github.com/users/EstherSeyi/orgs',
    repos_url: 'https://api.github.com/users/EstherSeyi/repos',
    events_url: 'https://api.github.com/users/EstherSeyi/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/EstherSeyi/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Empharez',
    id: 42961867,
    node_id: 'MDQ6VXNlcjQyOTYxODY3',
    avatar_url: 'https://avatars.githubusercontent.com/u/42961867?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Empharez',
    html_url: 'https://github.com/Empharez',
    followers_url: 'https://api.github.com/users/Empharez/followers',
    following_url:
      'https://api.github.com/users/Empharez/following{/other_user}',
    gists_url: 'https://api.github.com/users/Empharez/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Empharez/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Empharez/subscriptions',
    organizations_url: 'https://api.github.com/users/Empharez/orgs',
    repos_url: 'https://api.github.com/users/Empharez/repos',
    events_url: 'https://api.github.com/users/Empharez/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Empharez/received_events',
    type: 'User',
    site_admin: false,
  },
]
